### ISSUE TITLE
New Terminal windows default to the root user

### ISSUE THREAD

**Issue by dwaynebradley** [microsoft/vscode-remote-try-rust#4]
When creating a new Terminal window in VS Code by pressing ``Ctrl+Shift+` ``, the default user for the terminal is `root` because of how the Dockerfile is building the container.  This can lead to the chance of accidentally creating files in the container as `root` instead of the `vscode` user (which maps back to the local user).

Would it make sense to include the following `USER` statement to the end of the `.devcontainer/Dockerfile`:

```
USER $USERNAME
```
This way any new Terminal window that is created by VS Code automatically drops into the `vscode` user. Anything created in the Terminal windows would then have the correct permissions outside of the container.

Thoughts? Good/Bad?

If the answer is Good, maybe we should also replicate this across the `Dockerfile` in all of the `vscode-remote-try-<language>` repos as well.

**Comment by Chuxel** [comment]
Hmmmm. That should not be happening because of this in `devcontainer.json`:

```
"runArgs": [
		// Comment out the next line to run as root instead. Linux users, 
		// update Dockerfile with your user's UID/GID if not 1000.
		"-u", "vscode",
```

This allows you to specify the user the container starts as and you can switch between root and the non-root user without rebuilding the image.  

Is this missing from your devcontainer.json?  Also, this was not originally in the sample, so if you built it before, you may have an old container and need to run Remote-Containers: Rebuild Container.

Otherwise its strange this would happen.

**Comment by dwaynebradley** [comment]
Thanks @Chuxel. I had actually not even seen that option in `devcontainer.json` before! Thanks for pointing it out. Guess I should have read the comments better. :-)
